### ISSUE TITLE
Full node for embedded AI kits: plans and feasibility?

### ISSUE THREAD

**Issue by GillesJ** [grasslandnetwork/node_lite#3]
Recently AI GPU inferencing dev boards have become cheaper.

For instance, the Nvidia Jetson Nano dev kit looks like ideal node hardware.
It is optimized for GPU inferencing. It costs 99USD which is cheaper than paying for AWS long-term. Plus it hands more control to the administrator.
It runs Ubuntu and Nvidia's own Deepstream demo runs object detection on eight 1080p streams @ 30fps simultaneously. 

Grassland seems like an ideal use-case for this type of hardware.

- Are there plans to develop full-node source code?
- Are there any plans to produce an image for the Jetson specifically?

**Comment by 00hello** [comment]
> It runs Ubuntu and Nvidia's own Deepstream demo runs object detection on eight 1080p streams @ 30fps simultaneously.
> 

That is very cool!

> * Are there plans to develop full-node source code?

Yes there are. [This link](https://gist.github.com/00hello/0199d393e872ed7645979f5daf7bd62c) shows what needs to be built next by me or other people. A standalone node is going to be built soon. Just let me know if there's something you wanna tackle yourself.  And make a pull request if you have an improvement.

> * Are there any plans to produce an image for the Jetson specifically?

No plans yet. But once the standalone 'Node' is completed, it'll be a reference implementation so people can build images for specific hardware.

**Comment by GillesJ** [comment]
> Yes there are. [This link](https://gist.github.com/00hello/0199d393e872ed7645979f5daf7bd62c) shows what needs to be built next by me or other people. A standalone node is going to be built soon. Just let me know if there's something you wanna tackle yourself. And make a pull request if you have an improvement.

> No plans yet. But once the standalone 'Node' is completed, it'll be a reference implementation so people can build images for specific hardware.

Alright! I'll wait on the reference full node implementation before buying a Jetson and will attempt a port on my own.
